!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.JS_DOM=t():e.JS_DOM=t()}(window,function(){return function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}return n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s=0)}([function(e,t,n){"use strict";n.r(t);var r=function(){function e(e,t){for(var n=0;n<t.length;n++){var r=t[n];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(e,r.key,r)}}return function(t,n,r){return n&&e(t.prototype,n),r&&e(t,r),t}}();
/*!
 * JS DOM (JavaScript Library)
 *   js-dom.js
 * Version 0.0.5
 * Repository https://github.com/yama-dev/js-dom
 * Copyright yama-dev
 * Licensed under the MIT license.
 */
var o=function(){function e(){!function(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}(this,e)}return r(e,[{key:"isDom",value:function(e){try{return e instanceof HTMLElement}catch(e){return!1}}},{key:"isStr",value:function(e){try{return"string"==typeof e}catch(e){return!1}}},{key:"selectDom",value:function(e){var t=void 0;if(!Array.isArray(e)&&!e.length||this.isStr(e))t=this.isDom(e)?Array(e):Array.prototype.slice.call(document.querySelectorAll(e));else{if(!this.isDom(e[0]))return!1;t=Array.prototype.slice.call(e)}return t}},{key:"hasClass",value:function(e,t){return this.isDom(e)?e.classList.contains(t):document.querySelector(e).classList.contains(t)}},{key:"addClass",value:function(e,t){this.selectDom(e).map(function(e){e.classList.add(t)})}},{key:"removeClass",value:function(e,t){this.selectDom(e).map(function(e){e.classList.remove(t)})}},{key:"toggleClass",value:function(e,t){this.selectDom(e).map(function(e){e.classList.toggle(t)})}},{key:"setHtml",value:function(e,t){this.selectDom(e).map(function(e){e.innerHTML=t})}},{key:"appendHtml",value:function(e,t){this.selectDom(e).map(function(e){e.innerHTML+=t})}},{key:"addEvent",value:function(e,t,n){e===window?window.addEventListener(t,n):this.selectDom(e).map(function(e){e.addEventListener(t,n)})}},{key:"removeEvent",value:function(e,t,n){e===window?window.removeEventListener(t,n):this.selectDom(e).map(function(e){e.removeEventListener(t,n)})}},{key:"setStyle",value:function(e,t){this.selectDom(e).map(function(e){var n="";Object.keys(t).forEach(function(e){n+=e.replace(/([A-Z])/g,"-$1").toLowerCase()+":"+t[e]+";"}),e.setAttribute("style",n)})}}]),e}();t.default=o}]).default});